---
- name: clone certbot into configured directory
  git: repo="{{ certbot_repo }}"
       dest="{{ certbot_dir }}"
       version="{{ certbot_version }}"
       update="{{ certbot_keep_updated }}"

- name: ensure certbot-auto is executable
  file: path="{{ certbot_dir }}/certbot-auto"
        mode=0755
